# Form implementation generated from reading ui file 'orders_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 480)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(20, 370, 270, 34))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_add = QtWidgets.QPushButton(parent=self.widget2)
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout_4.addWidget(self.btn_add)
        self.btn_edit = QtWidgets.QPushButton(parent=self.widget2)
        self.btn_edit.setObjectName("btn_edit")
        self.horizontalLayout_4.addWidget(self.btn_edit)
        self.btn_delete = QtWidgets.QPushButton(parent=self.widget2)
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout_4.addWidget(self.btn_delete)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 20, 801, 321))
        self.scrollArea.setStyleSheet("background-color: rgb(244, 232, 211);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 797, 317))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_add.setStyleSheet(_translate("MainWindow", "font: 12pt \"Segoe UI\";"))
        self.btn_add.setText(_translate("MainWindow", "Добавить"))
        self.btn_edit.setStyleSheet(_translate("MainWindow", "font: 12pt \"Segoe UI\";"))
        self.btn_edit.setText(_translate("MainWindow", "Изменить"))
        self.btn_delete.setStyleSheet(_translate("MainWindow", "font: 12pt \"Segoe UI\";"))
        self.btn_delete.setText(_translate("MainWindow", "Удалить"))
